"""
worldRefactored.py — worldcode.py's generation primitives, ported to a hosted
`llama-server` (llama.cpp tools/server) using GBNF grammars + JSON-schema instead
of in-process logit surgery.

Design shift from worldcode.py
------------------------------
  * No in-process model, no KV manipulation, no rollback. Talk HTTP to llama-server.
  * Constrained generation via `grammar` (GBNF) / `json_schema`, NOT manual logit
    masking + token tries. This declaratively replaces promptNoun's stop-lists,
    parseNumber's number-token trie, getLocations2's huge stop set, etc.
  * `prsOfStrings` (full distribution over a candidate set via KV rollback) is
    DROPPED — it was a small-model hack. With a larger base model we just *pick*
    from the set with an alternation grammar (`pick_from_set`).
  * Probabilities (the old yesVsNo) come from `n_probs` on the first token.
  * Base-model friendly: raw continuation prompts, no chat template — which also
    deletes the old `"if was real"` fiction-puncturing fight (no RLHF to break char).
  * `cache_prompt=True` gives prefix reuse for free (replaces the manual eval/reset
    overlap logic in Model.eval).

Run a server first, e.g.:
  llama-server -m GLM-4-32B-Base.gguf -c 8192 --host 127.0.0.1 --port 8080

NOTE: the `n_probs` response schema has varied across llama.cpp versions
(`completion_probabilities` vs `logprobs`, `prob` vs `logprob`); `_first_token_probs`
parses defensively but check it against your build if `yes_no_prob` looks off.
"""

import re
import json
import math
import time
import datetime
import requests

import numbers_parse as nums   # number parsing copied wholesale from worldcode.py

SERVER_URL = "http://172.22.146.1:8055"

# Baked few-shot bank (generated by bootstrap_fewshot.py). Empty until bootstrapped —
# prompts then fall back to zero-shot. Few-shot priming teaches a base model the FORMAT
# (one sentence, no rambling) without anchoring the content, since examples are diverse.
try:
    from fewshot import FEWSHOT_CHARACTERS
except ImportError:
    FEWSHOT_CHARACTERS = []
FEWSHOT_N = 2   # only the character fields use few-shot; the schedule does not

# Explicit sampling sent on every request, overriding the server's configured sampler.
# temp 1 + top_k 0 + top_p 1 + min_p 0 + repeat_penalty 1 = the raw model distribution,
# no truncation or penalties.
DEFAULT_SAMPLING = {"temperature": 1.0, "top_k": 0, "top_p": 1.0, "min_p": 0.0, "repeat_penalty": 1.0}

# Local embeddinggemma server, for SEMANTIC dedup of generated locations:
#   llama-server -m embeddinggemma-300M-Q8_0.gguf --embedding --pooling mean --port 8062
EMBED_URL = "http://127.0.0.1:8062"


# ---------------------------------------------------------------------------
# GBNF grammar helpers  (these replace the hand-rolled stop-lists / token tries)
# ---------------------------------------------------------------------------

def gbnf_escape(s: str) -> str:
    """Escape a literal for a GBNF double-quoted string."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def alternation_grammar(options) -> str:
    """Force output to be exactly one of `options` (each with a LEADING space so it
    tokenizes naturally after 'Foo:', like YES_NO_GRAMMAR's " Yes"/" No"), then a "\\n"
    terminator. Terminator + stop=["\\n"] is what avoids the special-token crash."""
    alts = " | ".join(f'" {gbnf_escape(o.strip())}"' for o in options if o.strip())
    return f'root ::= ({alts}) "\\n"'


# Every grammar ENDS WITH A "\n" TERMINATOR, and callers pass stop=["\n"]. That halts
# generation the instant the grammar is satisfied — before the model can sample a stray
# special token (e.g. GLM-4's <|end_of_video|>) that underflows llama.cpp's grammar
# stack and crashes the server. (Confirmed fix; see LlamaServer.__init__.)
GRAMMAR_STOP = ["\n"]
YES_NO_GRAMMAR = 'root ::= (" Yes" | " No") "\\n"'
INT_GRAMMAR = 'root ::= "-"? [0-9]+ "\\n"'
INT_OR_RANGE_GRAMMAR = 'root ::= int (" - " int)? "\\n"\nint ::= "-"? [0-9]+'
# A location: any run of characters EXCEPT  /  "  ,  .  -  (and newline), then the terminator.
LOCATION_GRAMMAR = r'root ::= [^/",.\n-]+ "\n"'


# ---------------------------------------------------------------------------
# llama-server client
# ---------------------------------------------------------------------------

class LlamaServer:
    def __init__(self, url=SERVER_URL, sampling=None, seed=-1, timeout=120,
                 retries=4, retry_delay=2.0, use_grammar=True):
        self.url = url.rstrip("/")
        self.sampling = dict(DEFAULT_SAMPLING) if sampling is None else dict(sampling)
        self.seed = seed
        self.timeout = timeout
        self.retries = retries
        self.retry_delay = retry_delay
        # Grammar works on GLM-4-base + this llama.cpp build ONLY because every grammar
        # ends with a "\n" terminator and we stop on "\n" (GRAMMAR_STOP) — that halts
        # generation the instant the grammar is satisfied, BEFORE the model can sample a
        # stray special token (<|end_of_video|> etc.) that underflows the grammar stack
        # and crashes the server. Set use_grammar=False to fall back to free-gen + match.
        self.use_grammar = use_grammar

    def complete(self, prompt, grammar=None, json_schema=None, n_predict=64,
                 stop=None, temperature=None, n_probs=0, logit_bias=None,
                 cache_prompt=True, id_slot=-1):
        payload = {
            "prompt": prompt,
            "n_predict": n_predict,
            "cache_prompt": cache_prompt,
            "id_slot": id_slot,
            "seed": self.seed,
        }
        payload.update(self.sampling)   # explicit neutral sampler (temp 1, top_k 0, top_p 1, ...)
        if temperature is not None: payload["temperature"] = temperature
        if grammar is not None:     payload["grammar"] = grammar
        if json_schema is not None: payload["json_schema"] = json_schema
        if stop is not None:        payload["stop"] = stop
        if n_probs:                 payload["n_probs"] = n_probs
        if logit_bias is not None:  payload["logit_bias"] = logit_bias
        last = None
        for attempt in range(max(1, self.retries)):
            try:
                r = requests.post(self.url + "/completion", json=payload, timeout=self.timeout)
                r.raise_for_status()
                return r.json()
            except (requests.exceptions.RequestException, ValueError) as e:
                last = e
                time.sleep(self.retry_delay * (attempt + 1))
        raise last

    # --- free text (names, descriptions): bounded by stop + n_predict ---
    def gen_text(self, prompt, stop=None, n_predict=64, temperature=None, grammar=None):
        out = self.complete(prompt, grammar=grammar, stop=stop if stop is not None else ["\n"],
                            n_predict=n_predict, temperature=temperature)
        return clean_item(out.get("content", ""))

    # --- pick exactly one of a fixed set (replaces prsOfStrings selection) ---
    def pick_from_set(self, prompt, options, temperature=None):
        opts = [o.strip() for o in options if o.strip()]
        if not opts:
            return ""
        content = ""
        if self.use_grammar:
            # The grammar guarantees a valid option; retry a couple times if a flaky empty
            # response slips through (a 200 with empty content isn't an exception, so the
            # retry loop in complete() won't catch it).
            for _ in range(3):
                content = self.complete(prompt, grammar=alternation_grammar(opts),
                                        stop=GRAMMAR_STOP, n_predict=64,
                                        temperature=temperature).get("content", "").strip()
                if content in opts:
                    return content
                if content:
                    break   # non-empty but unmatched -> fuzzy-match below
        else:
            content = self.gen_text(prompt, stop=["\n", ".", "|", ",", ";"],
                                    n_predict=24, temperature=temperature)
        low = content.lower().strip()
        if low:                                  # NEVER fuzzy-match on empty content — that's
            for o in opts:                       # the bug that silently returned opts[0]
                if o.lower() == low:
                    return o
            for o in opts:
                if low in o.lower() or o.lower() in low:
                    return o
            rw = set(re.findall(r"\w+", low))
            best = max(opts, key=lambda o: len(rw & set(re.findall(r"\w+", o.lower()))))
            if rw & set(re.findall(r"\w+", best.lower())):
                return best
        return opts[0]   # explicit last resort (empty / no signal), not an accidental match

    # --- yes/no (hard answer) ---
    def yes_no(self, prompt, temperature=None):
        if self.use_grammar:
            out = self.complete(prompt, grammar=YES_NO_GRAMMAR, stop=GRAMMAR_STOP,
                                n_predict=5, temperature=temperature)
            return out.get("content", "").strip().lower().startswith("y")
        raw = self.gen_text(prompt, stop=["\n", ".", ","], n_predict=4, temperature=temperature)
        return raw.strip().lower().startswith("y")

    # --- yes/no probability (the old yesVsNo), done rigorously via first-token logprobs ---
    def yes_no_prob(self, prompt, n_probs=40):
        """P(yes) from the first answer token: sum the probability mass of all case/space
        variants of 'yes' vs 'no' — every token whose `.strip().lower()` is exactly 'yes' or
        'no' (' Yes', ' yes', ' YES', ... ; NOT 'yesterday'/'never'). n_predict=1; neutral
        sampling keeps the probs calibrated. (No grammar: llama.cpp reports the raw pre-grammar
        distribution in top_logprobs, so a grammar is a no-op here — the summing does the work.)"""
        out = self.complete(prompt, n_predict=1, n_probs=n_probs)
        yes = no = 0.0
        for tok, p in first_token_probs(out).items():
            t = tok.strip().lower()
            if t == "yes":
                yes += p
            elif t == "no":
                no += p
        return yes / (yes + no) if (yes + no) > 0 else 0.5

    # --- integer ---
    def gen_int(self, prompt, temperature=None):
        if self.use_grammar:
            raw = self.complete(prompt, grammar=INT_GRAMMAR, stop=GRAMMAR_STOP,
                               n_predict=16, temperature=temperature).get("content", "")
        else:
            raw = self.gen_text(prompt, stop=["\n", ".", ","], n_predict=12, temperature=temperature)
        m = re.search(r"-?\d+", raw)
        return int(m.group()) if m else None

    def gen_int_range(self, prompt, temperature=None):
        if self.use_grammar:
            raw = self.complete(prompt, grammar=INT_OR_RANGE_GRAMMAR, stop=GRAMMAR_STOP,
                               n_predict=24, temperature=temperature).get("content", "")
        else:
            raw = self.gen_text(prompt, stop=["\n"], n_predict=16, temperature=temperature)
        ns = [int(x) for x in re.findall(r"-?\d+", raw)]
        return (min(ns), max(ns)) if ns else None

    def gen_number(self, prompt):
        """Generate a number answer constrained by nums.NUMBER_GRAMMAR (number words OR digits,
        magnitudes, ranges) and parse it with the wholesale-copied worldcode.py parser into a
        WeightedRange (.minVal / .maxVal / .sample()). None if it fails to parse. Only the
        generation changed from the original parseNumber (token-trie + greedy/topN) -> grammar."""
        raw = self.gen_text(prompt, stop=GRAMMAR_STOP, n_predict=32,
                            grammar=nums.NUMBER_GRAMMAR if self.use_grammar else None)
        try:
            return nums.parseIntRangeFromText(raw)
        except Exception:
            return None

    # --- list of items ---
    # NB: JSON-schema also compiles to a grammar and would hit the same special-token
    # crash, so we generate a newline list and split (terminator-safe via "\n\n" stop).
    def gen_list(self, prompt, n, temperature=None):
        out = self.complete(prompt, stop=["\n\n"], n_predict=40 * n, temperature=temperature)
        items = [clean_item(re.sub(r"^[-*\d.\)\s]+", "", x)) for x in out.get("content", "").split("\n")]
        return [x for x in items if x][:n]


# ---------------------------------------------------------------------------
# small text utilities (trimmed from worldcode.py — most cleanup is now unneeded)
# ---------------------------------------------------------------------------

def clean_item(item: str) -> str:
    item = item.split("<|")[0]                  # cut any leaked special token (<|end_of_text|> ...)
    item = re.sub(r"\s+", " ", item.strip())
    item = re.sub(r"[.]$", "", item).strip()
    return item


def first_token_probs(completion_json) -> dict:
    """{token_str: prob} for the first generated token, defensive across schemas."""
    cp = completion_json.get("completion_probabilities") or completion_json.get("logprobs")
    if not cp:
        return {}
    cand = cp[0].get("probs") or cp[0].get("top_logprobs") or []
    out = {}
    for c in cand:
        tok = c.get("tok") or c.get("token") or c.get("text") or ""
        if "prob" in c:
            out[tok] = c["prob"]
        elif "logprob" in c:
            out[tok] = math.exp(c["logprob"])
    return out


def embed_texts(texts, url=EMBED_URL, timeout=30):
    """Embed texts via the local embeddinggemma server (OpenAI-style /v1/embeddings).
    Uses embeddinggemma's document prompt format. Returns a list of vectors."""
    inp = [f"title: none | text: {t}" for t in texts]
    r = requests.post(url.rstrip("/") + "/v1/embeddings", json={"input": inp}, timeout=timeout)
    r.raise_for_status()
    return [d["embedding"] for d in r.json()["data"]]


def cosine(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    na = sum(x * x for x in a) ** 0.5
    nb = sum(y * y for y in b) ** 0.5
    return dot / (na * nb) if na and nb else 0.0


# ---------------------------------------------------------------------------
# Character generation  (base-model continuation prompts + grammars)
# ---------------------------------------------------------------------------

PRONOUN = {"female": ("She", "Her"), "male": ("He", "His")}


def pron(gender):
    return PRONOUN.get(gender, ("They", "Their"))


# Each field's query template ends with ": "; for a few-shot example we append the
# example's value. {placeholders} are filled from the (growing) context dict. Tuple is
# (template, stop-strings, n_predict).
# Templates END WITHOUT a trailing space — a base model tokenizes the value with a
# LEADING space (" Veretta" is one token), so ending on a space forces a no-leading-space
# token and produces garbage. gen_field adds the separating space before the value, so
# example and query agree on the tokenization.
FIELDS = {
    "name":        ("Setting: {world}\n"
                    "There was once a {gender} {species} named",
                    ["\n", ".", ",", ";", " who", " that", " which", " from", " lived", " was"], 12),
    "appearance":  ("Setting: {world}\nSpecies: {species}\nGender: {gender}\nCharacter: {name}\n"
                    "In one sentence, {name}'s physical appearance:", ["\n"], 64),
    "personality": ("Setting: {world}\nSpecies: {species}\nGender: {gender}\nCharacter: {name}\n"
                    "Appearance: {appearance}\n"
                    "In one sentence, {name}'s personality:", ["\n"], 64),
    "backstory":   ("Setting: {world}\nSpecies: {species}\nGender: {gender}\nCharacter: {name}\n"
                    "Personality: {personality}\n"
                    "In one sentence, {name}'s backstory:", ["\n"], 96),
}

# Resample a field whose output is rejected by REJECT[field] (a predicate -> True means resample).
# A name is bad if it's empty/too short, literally "name"/"named", or contains the word "and"
# (the model listed two names rather than one). \band\b spares Andrew/Sandra/Alexander.
def _name_is_bad(v):
    s = v.strip().lower()
    return len(s) < 2 or s in ("name", "named") or re.search(r"\band\b", v, re.I) is not None


def non_english(v):
    """True if the text is substantially non-Latin-script (CJK / Cyrillic / etc.) — GLM
    sometimes emits all-Chinese output. Common accented Latin (José, Müller) still passes,
    since those codepoints sit at/below Latin Extended-B (<= 0x024F)."""
    letters = [c for c in v if c.isalpha()]
    if not letters:
        return False
    non_latin = sum(1 for c in letters if ord(c) > 0x024F)
    return non_latin / len(letters) > 0.2


REJECT = {"name": _name_is_bad}


def field_prompt(field, ctx, examples=None):
    """Build the few-shot prompt gen_field sends for a character field — exposed so a UI can
    show it for debugging."""
    tmpl = FIELDS[field][0]
    ex = (FEWSHOT_CHARACTERS if examples is None else examples)[:FEWSHOT_N]
    shots = [tmpl.format(**e) + " " + e[field] for e in ex]   # space -> value is a leading-space token
    return ("\n\n".join(shots) + "\n\n" if shots else "") + tmpl.format(**ctx)


def gen_field(server, field, ctx, examples=None, tries=5):
    """Generate one character field, primed with up to FEWSHOT_N baked examples. Resamples (up
    to `tries`) if the result is non-English (GLM sometimes emits all-Chinese) or matches
    REJECT[field] (e.g. a bad name: empty, 'name', or has 'and')."""
    _, stops, npred = FIELDS[field]
    prompt = field_prompt(field, ctx, examples)
    rej = REJECT.get(field)
    val = server.gen_text(prompt, stop=stops, n_predict=npred)
    for _ in range(tries - 1):
        if not non_english(val) and not (rej and rej(val)):
            break
        val = server.gen_text(prompt, stop=stops, n_predict=npred)
    return val


def char_prefix(d) -> str:
    return (f"Setting: {d['world']}\nCharacter: {d['name']}\nSpecies: {d['species']}\n"
            f"Gender: {d['gender']}\n"
            f"Appearance: {d['appearance']}\nPersonality: {d['personality']}\n"
            f"Backstory: {d['backstory']}")


class Character:
    def __init__(self, server: LlamaServer, world, gender, species="human", name=None,
                 examples=None):
        self.world, self.gender, self.species = world, gender, species
        ctx = {"world": world, "species": species, "gender": gender}
        ctx["name"] = self.name = name or gen_field(server, "name", ctx, examples)
        ctx["appearance"] = self.appearance = gen_field(server, "appearance", ctx, examples)
        ctx["personality"] = self.personality = gen_field(server, "personality", ctx, examples)
        ctx["backstory"] = self.backstory = gen_field(server, "backstory", ctx, examples)
        self.fields = ctx
        self.prefix = char_prefix(ctx)

    def needs_food(self, server):
        return server.yes_no(self.prefix + f"\nQuestion: Does {self.name} need to eat? Answer:")

    def __repr__(self):
        return self.prefix


def make_times(start, steps, **interval):
    times = [start]
    for _ in range(steps):
        start = start + datetime.timedelta(**interval)
        times.append(start)
    return times


def locations_prompt(character):
    """The fixed one-item prompt iter_locations re-samples from (exposed for debugging)."""
    subj = pron(character.gender)[0].lower()
    return (character.prefix +
            f"\nList the types of locations that {subj} frequently visits (each 1-5 words):\n"
            f"{character.name} can be found in the following types of locations:\n-")


def iter_locations(server, character, n=12, max_attempts=None,
                   sim_threshold=0.78, embed_url=EMBED_URL):
    """Generator form of gen_locations — yields each accepted location as it is found, so a
    UI can stream them. The base model derails if asked for a whole list, so we read ONLY the
    first bullet from a FIXED one-item prompt and re-sample (the prompt never grows; diversity
    comes from sampling, cache_prompt keeps it cheap). Near-duplicates ('Deep Sea Trenches' ~
    'deep-sea trenches') are collapsed by SEMANTIC dedup: each candidate is embedded
    (embeddinggemma) and skipped if cosine similarity to a kept location >= sim_threshold.
    Falls back to exact dedup if the embed server is down. Replaces the original's huge stop
    set + singularize/strip-descriptive machinery."""
    prompt = locations_prompt(character)
    embs, seen, count = [], set(), 0
    for _ in range(max_attempts or n * 5):
        if count >= n:
            break
        raw = server.gen_text(prompt, stop=["\n"], n_predict=16,
                              grammar=LOCATION_GRAMMAR if server.use_grammar else None)
        item = clean_item(re.sub(r"\s*\(.*?\)", "", raw))
        words = item.split()
        if words and words[0].lower() in ("the", "a", "an"):   # strip leading article (as original)
            item = " ".join(words[1:])
        if not item or len(item) > 40 or item.lower() in seen or non_english(item):
            continue
        try:                                               # semantic dedup against kept locations
            e = embed_texts([item], embed_url)[0]
            if embs and max(cosine(e, pe) for pe in embs) >= sim_threshold:
                continue
        except Exception:
            e = None                                       # embed server down -> exact dedup only
        seen.add(item.lower())
        if e is not None:
            embs.append(e)
        count += 1
        yield item


def gen_locations(server, character, n=12, **kwargs):
    """List form of iter_locations (collects all n locations before returning)."""
    return list(iter_locations(server, character, n, **kwargs))


def sleep_prompt(character, location):
    """The yes/no question scoring whether the character sleeps at `location`."""
    return character.prefix + f"\n\nQuestion: Does {character.name} sleep at {location}? Answer:"


def sleep_prob(server, character, location):
    """P(the character sleeps at this location), via yes_no_prob."""
    return server.yes_no_prob(sleep_prompt(character, location))


def nocturnal_prompt(character):
    """The yes/no question scoring whether the character is nocturnal."""
    return character.prefix + f"\n\nQuestion: Is {character.name} nocturnal? Answer:"


def nocturnal_prob(server, character):
    """P(the character is nocturnal), via yes_no_prob."""
    return server.yes_no_prob(nocturnal_prompt(character))


def presence_prompt(character, location, time_str):
    """Yes/no question: is the character likely to be at `location` at `time_str`?"""
    return character.prefix + f"\n\nQuestion: At {time_str}, is {character.name} likely to be at {location}? Answer:"


def presence_prob(server, character, location, time_str):
    """P(the character is at this location at this time of day), via yes_no_prob."""
    return server.yes_no_prob(presence_prompt(character, location, time_str))


def ever_prompt(character, location):
    """Yes/no question: is the character EVER at `location` (day or night)?"""
    return character.prefix + f"\n\nQuestion: Is {character.name} ever at {location}, day or night? Answer:"


def ever_prob(server, character, location):
    """P(the character ever goes to this location at all), via yes_no_prob. Used to pre-filter
    the locations down to the few worth scoring hour-by-hour."""
    return server.yes_no_prob(ever_prompt(character, location))


def gen_schedule(server: LlamaServer, character: Character, times, locations=None):
    """Port of promptSchedule. The time-grid is the structure; the model fills each
    present-tense slot; the location is PICKED from the known set via a grammar
    (replacing the old prsOfStrings probability read). Past-tense framing
    ("did yesterday") is preserved — it collapses the model into specificity. No
    few-shot here: a schedule example just primes the model to stay in one place.
    If `locations` is None, they're generated for the character via gen_locations."""
    if locations is None:
        locations = gen_locations(server, character)
    name = character.name
    durs = [f"{a.strftime('%I:%M %p')}-{b.strftime('%I:%M %p')}"
            for a, b in zip(times, times[1:])]
    prompt = character.prefix + f"\n\nThis is what {name} did yesterday:\n"
    schedule = []
    for dur in durs:
        action = server.gen_text(prompt + dur + ":", stop=["\n", "|", "("], n_predict=40)
        loc = server.pick_from_set(prompt + dur + ": " + action + ". Location:", locations)
        schedule.append((dur, action, loc))
        prompt = prompt + dur + ": " + action + " | Location: " + loc + "\n"
    return schedule


# ---------------------------------------------------------------------------
# demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    srv = LlamaServer()
    world = "A medieval fantasy mushroom kingdom"
    locations = ["Nest", "Mushroom Market", "Spore Caves", "Riverbank", "Mycelium Hall"]

    eugene = Character(srv, world, gender="female", species="giant isopod")
    print(eugene, "\n")
    print("needs food?", eugene.needs_food(srv))

    times = make_times(datetime.datetime.strptime("08:00", "%H:%M"), 12, hours=1)
    for dur, action, loc in gen_schedule(srv, eugene, times, locations):
        print(f"{dur}: {action}  |  {loc}")
