"""
worldRefactored.py — worldgen / domain code (characters, locations, objects, schedules, NPC
counts) built on the base-model primitives in baseModelPrimitives.py. The low-level
LlamaServer client + the logprob/number/percent primitives + grammar/embedding helpers now
live there; this module is just the prompts + generators that USE them.
"""

import re
import datetime

from baseModelPrimitives import (
    LlamaServer, SERVER_URL, EMBED_URL, LOCATION_GRAMMAR,
    clean_item, embed_texts, cosine,
)


# Baked few-shot bank (generated by bootstrap_fewshot.py). Empty until bootstrapped —
# prompts then fall back to zero-shot. Few-shot priming teaches a base model the FORMAT
# (one sentence, no rambling) without anchoring the content, since examples are diverse.
try:
    from fewshot import FEWSHOT_CHARACTERS
except ImportError:
    FEWSHOT_CHARACTERS = []
FEWSHOT_N = 2   # only the character fields use few-shot; the schedule does not


# ---------------------------------------------------------------------------
# Character generation  (base-model continuation prompts + grammars)
# ---------------------------------------------------------------------------

PRONOUN = {"female": ("She", "Her"), "male": ("He", "His")}


def pron(gender):
    return PRONOUN.get(gender, ("They", "Their"))


# Each field's query template ends with ": "; for a few-shot example we append the
# example's value. {placeholders} are filled from the (growing) context dict. Tuple is
# (template, stop-strings, n_predict).
# Templates END WITHOUT a trailing space — a base model tokenizes the value with a
# LEADING space (" Veretta" is one token), so ending on a space forces a no-leading-space
# token and produces garbage. gen_field adds the separating space before the value, so
# example and query agree on the tokenization.
FIELDS = {
    "name":        ("Setting: {world}\n"
                    "There was once a {gender} {species} named",
                    ["\n", ".", ",", ";", " who", " that", " which", " from", " lived", " was"], 12),
    "appearance":  ("Setting: {world}\nSpecies: {species}\nGender: {gender}\nCharacter: {name}\n"
                    "In one sentence, {name}'s physical appearance:", ["\n"], 64),
    "personality": ("Setting: {world}\nSpecies: {species}\nGender: {gender}\nCharacter: {name}\n"
                    "Appearance: {appearance}\n"
                    "In one sentence, {name}'s personality:", ["\n"], 64),
    "backstory":   ("Setting: {world}\nSpecies: {species}\nGender: {gender}\nCharacter: {name}\n"
                    "Personality: {personality}\n"
                    "In one sentence, {name}'s backstory:", ["\n"], 96),
}

# Resample a field whose output is rejected by REJECT[field] (a predicate -> True means resample).
# A name is bad if it's empty/too short, literally "name"/"named", or contains the word "and"
# (the model listed two names rather than one). \band\b spares Andrew/Sandra/Alexander.
def _name_is_bad(v):
    s = v.strip().lower()
    return len(s) < 2 or s in ("name", "named") or re.search(r"\band\b", v, re.I) is not None


def non_english(v):
    """True if the text is substantially non-Latin-script (CJK / Cyrillic / etc.) — GLM
    sometimes emits all-Chinese output. Common accented Latin (José, Müller) still passes,
    since those codepoints sit at/below Latin Extended-B (<= 0x024F)."""
    letters = [c for c in v if c.isalpha()]
    if not letters:
        return False
    non_latin = sum(1 for c in letters if ord(c) > 0x024F)
    return non_latin / len(letters) > 0.2


REJECT = {"name": _name_is_bad}


def field_prompt(field, ctx, examples=None):
    """Build the few-shot prompt gen_field sends for a character field — exposed so a UI can
    show it for debugging."""
    tmpl = FIELDS[field][0]
    ex = (FEWSHOT_CHARACTERS if examples is None else examples)[:FEWSHOT_N]
    shots = [tmpl.format(**e) + " " + e[field] for e in ex]   # space -> value is a leading-space token
    return ("\n\n".join(shots) + "\n\n" if shots else "") + tmpl.format(**ctx)


def gen_field(server, field, ctx, examples=None, tries=5):
    """Generate one character field, primed with up to FEWSHOT_N baked examples. Resamples (up
    to `tries`) if the result is non-English (GLM sometimes emits all-Chinese) or matches
    REJECT[field] (e.g. a bad name: empty, 'name', or has 'and')."""
    _, stops, npred = FIELDS[field]
    prompt = field_prompt(field, ctx, examples)
    rej = REJECT.get(field)
    val = server.gen_text(prompt, stop=stops, n_predict=npred)
    for _ in range(tries - 1):
        if not non_english(val) and not (rej and rej(val)):
            break
        val = server.gen_text(prompt, stop=stops, n_predict=npred)
    return val


def char_prefix(d) -> str:
    return (f"Setting: {d['world']}\nCharacter: {d['name']}\nSpecies: {d['species']}\n"
            f"Gender: {d['gender']}\n"
            f"Appearance: {d['appearance']}\nPersonality: {d['personality']}\n"
            f"Backstory: {d['backstory']}")


class Character:
    def __init__(self, server: LlamaServer, world, gender, species="human", name=None,
                 examples=None):
        self.world, self.gender, self.species = world, gender, species
        ctx = {"world": world, "species": species, "gender": gender}
        ctx["name"] = self.name = name or gen_field(server, "name", ctx, examples)
        ctx["appearance"] = self.appearance = gen_field(server, "appearance", ctx, examples)
        ctx["personality"] = self.personality = gen_field(server, "personality", ctx, examples)
        ctx["backstory"] = self.backstory = gen_field(server, "backstory", ctx, examples)
        self.fields = ctx
        self.prefix = char_prefix(ctx)

    def needs_food(self, server):
        return server.yes_no(self.prefix + f"\nQuestion: Does {self.name} need to eat? Answer:")

    def __repr__(self):
        return self.prefix


def make_times(start, steps, **interval):
    times = [start]
    for _ in range(steps):
        start = start + datetime.timedelta(**interval)
        times.append(start)
    return times


def locations_prompt(character):
    """The fixed one-item prompt iter_locations re-samples from (exposed for debugging)."""
    subj = pron(character.gender)[0].lower()
    return (character.prefix +
            f"\nList the types of locations that {subj} frequently visits (each 1-5 words):\n"
            f"{character.name} can be found in the following types of locations:\n-")


def iter_locations(server, character, n=12, max_attempts=None,
                   sim_threshold=0.78, embed_url=EMBED_URL):
    """Generator form of gen_locations — yields each accepted location as it is found, so a
    UI can stream them. The base model derails if asked for a whole list, so we read ONLY the
    first bullet from a FIXED one-item prompt and re-sample (the prompt never grows; diversity
    comes from sampling, cache_prompt keeps it cheap). Near-duplicates ('Deep Sea Trenches' ~
    'deep-sea trenches') are collapsed by SEMANTIC dedup: each candidate is embedded
    (embeddinggemma) and skipped if cosine similarity to a kept location >= sim_threshold.
    Falls back to exact dedup if the embed server is down. Replaces the original's huge stop
    set + singularize/strip-descriptive machinery."""
    prompt = locations_prompt(character)
    embs, seen, count = [], set(), 0
    for _ in range(max_attempts or n * 5):
        if count >= n:
            break
        raw = server.gen_text(prompt, stop=["\n"], n_predict=16,
                              grammar=LOCATION_GRAMMAR if server.use_grammar else None)
        item = clean_item(re.sub(r"\s*\(.*?\)", "", raw))
        words = item.split()
        if words and words[0].lower() in ("the", "a", "an"):   # strip leading article (as original)
            item = " ".join(words[1:])
        if not item or len(item) > 40 or item.lower() in seen or non_english(item):
            continue
        try:                                               # semantic dedup against kept locations
            e = embed_texts([item], embed_url)[0]
            if embs and max(cosine(e, pe) for pe in embs) >= sim_threshold:
                continue
        except Exception:
            e = None                                       # embed server down -> exact dedup only
        seen.add(item.lower())
        if e is not None:
            embs.append(e)
        count += 1
        yield item


def gen_locations(server, character, n=12, **kwargs):
    """List form of iter_locations (collects all n locations before returning)."""
    return list(iter_locations(server, character, n, **kwargs))


def objects_prompt(world, location):
    """Fixed one-item prompt for the types of objects found in a location (re-sampled like
    locations: minecarts/tracks/debris for a mine, tables/chairs/wares for a storefront)."""
    return (f"Setting: {world}\nLocation: {location}\n"
            f"List the types of objects found in {location} (each 1-5 words):\n"
            f"In {location} you would find the following objects:\n-")


def iter_objects(server, world, location, n=12, max_attempts=None,
                 sim_threshold=0.78, embed_url=EMBED_URL):
    """Generate the types of objects present at a location — same one-bullet-at-a-time re-sample
    + semantic dedup (embeddinggemma) as iter_locations, seeded with the world + location."""
    prompt = objects_prompt(world, location)
    embs, seen, count = [], set(), 0
    for _ in range(max_attempts or n * 5):
        if count >= n:
            break
        raw = server.gen_text(prompt, stop=["\n"], n_predict=16,
                             grammar=LOCATION_GRAMMAR if server.use_grammar else None)
        item = clean_item(re.sub(r"\s*\(.*?\)", "", raw))
        words = item.split()
        if words and words[0].lower() in ("the", "a", "an"):
            item = " ".join(words[1:])
        if not item or len(item) > 40 or item.lower() in seen or non_english(item):
            continue
        try:
            e = embed_texts([item], embed_url)[0]
            if embs and max(cosine(e, pe) for pe in embs) >= sim_threshold:
                continue
        except Exception:
            e = None
        seen.add(item.lower())
        if e is not None:
            embs.append(e)
        count += 1
        yield item


def gen_objects(server, world, location, n=12, **kwargs):
    """List form of iter_objects."""
    return list(iter_objects(server, world, location, n, **kwargs))


def sleep_prompt(character, location):
    """The yes/no question scoring whether the character sleeps at `location`."""
    return character.prefix + f"\n\nQuestion: Does {character.name} sleep at {location}? Answer:"


def sleep_prob(server, character, location):
    """P(the character sleeps at this location), via yes_no_prob."""
    return server.yes_no_prob(sleep_prompt(character, location))


def nocturnal_prompt(character):
    """The yes/no question scoring whether the character is nocturnal."""
    return character.prefix + f"\n\nQuestion: Is {character.name} nocturnal? Answer:"


def nocturnal_prob(server, character):
    """P(the character is nocturnal), via yes_no_prob."""
    return server.yes_no_prob(nocturnal_prompt(character))


def presence_prompt(character, location, time_str):
    """Yes/no question: is the character likely to be at `location` at `time_str`?"""
    return character.prefix + f"\n\nQuestion: At {time_str}, is {character.name} likely to be at {location}? Answer:"


def presence_prob(server, character, location, time_str):
    """P(the character is at this location at this time of day), via yes_no_prob."""
    return server.yes_no_prob(presence_prompt(character, location, time_str))


def ever_prompt(character, location):
    """Yes/no question: is the character EVER at `location` (day or night)?"""
    return character.prefix + f"\n\nQuestion: Is {character.name} ever at {location}, day or night? Answer:"


def ever_prob(server, character, location):
    """P(the character ever goes to this location at all), via yes_no_prob. Used to pre-filter
    the locations down to the few worth scoring hour-by-hour."""
    return server.yes_no_prob(ever_prompt(character, location))


def npc_count_prompt(world, location):
    """Number question: over a full day, how many different NPCs are present in `location`?
    ("NPCs", not "people", so it fits non-human settings; "different ... over a full day" =
    distinct individuals across the day.) Sampled via gen_number_median + the copied parser."""
    return (f"Setting: {world}\nLocation: {location}\n"
            f"Question: Over a full day, how many different NPCs are present in {location}?\nAnswer:")


def gen_schedule(server: LlamaServer, character: Character, times, locations=None):
    """Port of promptSchedule. The time-grid is the structure; the model fills each
    present-tense slot; the location is PICKED from the known set via a grammar
    (replacing the old prsOfStrings probability read). Past-tense framing
    ("did yesterday") is preserved — it collapses the model into specificity. No
    few-shot here: a schedule example just primes the model to stay in one place.
    If `locations` is None, they're generated for the character via gen_locations."""
    if locations is None:
        locations = gen_locations(server, character)
    name = character.name
    durs = [f"{a.strftime('%I:%M %p')}-{b.strftime('%I:%M %p')}"
            for a, b in zip(times, times[1:])]
    prompt = character.prefix + f"\n\nThis is what {name} did yesterday:\n"
    schedule = []
    for dur in durs:
        action = server.gen_text(prompt + dur + ":", stop=["\n", "|", "("], n_predict=40)
        loc = server.pick_from_set(prompt + dur + ": " + action + ". Location:", locations)
        schedule.append((dur, action, loc))
        prompt = prompt + dur + ": " + action + " | Location: " + loc + "\n"
    return schedule


# ---------------------------------------------------------------------------
# demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    srv = LlamaServer()
    world = "A medieval fantasy mushroom kingdom"
    locations = ["Nest", "Mushroom Market", "Spore Caves", "Riverbank", "Mycelium Hall"]

    eugene = Character(srv, world, gender="female", species="giant isopod")
    print(eugene, "\n")
    print("needs food?", eugene.needs_food(srv))

    times = make_times(datetime.datetime.strptime("08:00", "%H:%M"), 12, hours=1)
    for dur, action, loc in gen_schedule(srv, eugene, times, locations):
        print(f"{dur}: {action}  |  {loc}")
